---
- name: Set modules default configuration on Linux
  set_fact:
    metricbeat_modules_default_config: "{{ metricbeat_modules_default_config | combine(metricbeat_additional_default_config) }}"
  when: ansible_system == "Linux"

- name: Set modules default configuration on Windows
  set_fact:
    metricbeat_modules_default_config: "{{ metricbeat_modules_default_config | combine(metricbeat_win_additional_default_config) }}"
  when: ansible_os_family == "Windows"

- name: Set modules config from configured variable
  set_fact:
    metricbeat_modules_config: "{{ metricbeat_modules_config | combine({item: lookup('vars', 'metricbeat_module_' + item).config}) }}"
  loop: "{{ metricbeat_supported_modules }}"
  when: lookup('vars', 'metricbeat_module_' + item).enabled == true and lookup('vars', 'metricbeat_module_' + item).config is defined

- name: Set modules config from default variable if not configures
  set_fact:
    metricbeat_modules_config: "{{ metricbeat_modules_config | combine( {item: metricbeat_modules_default_config[item]} ) }}"
  loop: "{{ metricbeat_supported_modules }}"
  when: lookup('vars', 'metricbeat_module_' + item).enabled == true and lookup('vars', 'metricbeat_module_' + item).config is not defined

- import_tasks: configure-modules-Linux.yml
  when: ansible_system == "Linux"

- import_tasks: configure-modules-Windows.yml
  when: ansible_os_family == "Windows"
