---
- name: Disable disabled Metricbeat modules
  ansible.builtin.file:
    path: "{{ metricbeat_modules_path }}/{{ item }}.yml"
    state: absent
  loop: "{{ metricbeat_modules_disabled }}"
  notify: Restart Metricbeat

- name: Enable enabled Metricbeat module
  ansible.builtin.copy:
    src: "{{ metricbeat_modules_path }}/{{ item }}.yml.disabled"
    dest: "{{ metricbeat_modules_path }}/{{ item }}.yml"
    mode: '0644'
  loop: "{{ metricbeat_modules_enabled }}"
  user: root
  group: root
  mode: '0644'
  notify: Restart Metricbeat

- name: Configure modules with custom configuration
  ansible.builtin.template:
    src: "templates/module.yml.j2"
    dest: "{{ metricbeat_modules_path }}/{{ item }}.yml"
    mode: '0644'
  vars:
    module_name: "{{ item }}"
    module_config: "{{ metricbeat_modules_config[item] }}"
  loop: "{{ metricbeat_modules_enabled }}"
  user: root
  group: root
  mode: '0644'
  notify: Restart Metricbeat

- name: Enable the system module when not explicitly disabled
  ansible.builtin.template:
    src: "templates/module-system.yml.j2"
    dest: "{{ metricbeat_modules_path }}/system.yml"
    mode: '0644'
  user: root
  group: root
  mode: '0644'
  notify: Restart Metricbeat
  when: "'system' not in metricbeat_modules_disabled"
