---
- name: Configure Metricbeat
  ansible.builtin.template:
    src: templates/metricbeat.yml.j2
    dest: "{{ metricbeat_conf_path }}/metricbeat.yml"
    mode: '0644'
  notify: Restart Metricbeat

- name: Setup Index and other Elasticsearch stuff
  ansible.builtin.command:
    cmd: metricbeat setup --index-management
  changed_when: false
  when: metricbeat_setup_index

- name: Setup Kibana Dashboards
  ansible.builtin.command:
    cmd: metricbeat setup --dashboards
  changed_when: false
  when: metricbeat_setup_dashboards
