---
- name: Disable disabled Metricbeat modules
  file:
    path: "{{ metricbeat_modules_path }}/{{ item }}.yml"
    state: absent
  loop: "{{ metricbeat_supported_modules }}"
  when: item not in metricbeat_modules or (item in metricbeat_modules and metricbeat_modules[item].enabled != true)
  notify: Restart Metricbeat

- name: Enable and configure enabled Metricbeat modules
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ metricbeat_modules_path }}/{{ item }}.yml"
  loop: "{{ metricbeat_supported_modules }}"
  when: item in metricbeat_modules and (metricbeat_modules[item].enabled is undefined or metricbeat_modules[item].enabled == true)
  notify: Restart Metricbeat
