---
- include_tasks: install-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: install-Redhat.yml
  when: ansible_os_family == "Redhat"

- name: Ensure Metricbeat is started and enabled on boot
  service:
    name: metricbeat
    state: started
    enabled: "{{ metricbeat_enable_on_boot }}"
