---
- name: Install Elasticsearch repository
  ansible.builtin.include_role:
    name: mmartinello.elastic
  vars:
    elastic_major_version: "{{ metricbeat_major_version }}"

- name: Install Metricbeat
  ansible.builtin.apt:
    name: metricbeat
    state: present
  notify: Restart Metricbeat
