---
- name: Install Metricbeat using Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: metricbeat-oss
    version: "{{ metricbeat_win_chocolatey_version }}"
  notify: Restart Metricbeat on Windows

- name: Set Metricbeat variables
  ansible.builtin.set_fact:
    metricbeat_win_conf_path: "C:\\Program\ Files\\Elastic\\Beats\\{{ metricbeat_win_chocolatey_version }}\\metricbeat"
    metricbeat_win_modules_path: "C:\\Program\ Files\\Elastic/Beats\\{{ metricbeat_win_chocolatey_version }}\\metricbeat/modules.d"

- name: Debug metricbeat_win_conf_path
  ansible.builtin.debug:
    var: metricbeat_win_conf_path

- name: Check if install-service-metricbeat.ps1 exists
  ansible.windows.win_stat:
    path: "{{ metricbeat_win_conf_path }}\\install-service-metricbeat.ps1"
  register: metricbeat_script

- name: Debug script existence
  ansible.builtin.debug:
    var: metricbeat_script

- name: Install Metricbeat service
  ansible.windows.win_shell: '"{{ metricbeat_win_conf_path }}\\install-service-metricbeat.ps1"'
  args:
    #chdir: "{{ metricbeat_win_conf_path }}"

- name: Ensure Metricbeat is started and enabled on boot.
  ansible.windows.win_service:
    name: metricbeat
    state: started
    start_mode: "{{ _metricbeat_win_start_mode }}"
  when: ansible_os_family == "Windows"
