---
- name: Install Elasticsearch repository
  ansible.builtin.include_role:
    name: mmartinello.elastic
  vars:
    elastic_major_version: "{{ metricbeat_major_version }}"

- name: Install Metricbeat
  ansible.builtin.apt:
    name: metricbeat
    state: present
  notify: Restart Metricbeat

# Service startup
- name: Ensure Metricbeat is started and enabled on boot
  ansible.builtin.service:
    name: metricbeat
    state: started
    enabled: "{{ metricbeat_enable_on_boot }}"
  when: ansible_system == "Linux"
