---
- name: Install dependencies
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch APT Key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic APT Repository
  ansible.builtin.add_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ metricbeat_major_version }}.x/apt stable main'
    filename: elastic
    state: present
    update_cache: true

- name: Install Metricbeat
  ansible.builtin.apt:
    name: metricbeat
    state: present
  notify: Restart Metricbeat
