---
- name: Install on Debian
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == "Debian"

- name: Install on Redhat
  ansible.builtin.include_tasks: install-Redhat.yml
  when: ansible_os_family == "Redhat"

- name: Install on Windows
  ansible.builtin.include_tasks: install-Windows.yml
  when: ansible_os_family == "Windows"
