---
- include_tasks: install-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: install-Redhat.yml
  when: ansible_os_family == "Redhat"

- include_tasks: install-Windows.yml
  when: ansible_os_family == "Windows"
