---
# Install
- import_tasks: install.yml
  tags: ['install']

# Configure
- import_tasks: configure.yml
  tags: ['configure']

# Configure Modules
- import_tasks: configure-modules.yml
  tags: ['configure', 'modules']
