---
# Variables
- name: Import variables
  ansible.builtin.import_tasks: vars.yml
  tags: ['always']

# Install
- name: Install Metricbeat
  ansible.builtin.include_tasks: install.yml
  tags: ['install']

# Configure
- name: Configure Metricbeat
  ansible.builtin.include_tasks: configure.yml
  tags: ['configure']

# Configure Modules
- name: Configure Metricbeat modules
  ansible.builtin.include_tasks: configure-modules.yml
  tags: ['configure', 'modules']

# Service startup
- name: Ensure Metricbeat is started and enabled on boot
  ansible.builtin.service:
    name: metricbeat
    state: started
    enabled: "{{ metricbeat_enable_on_boot }}"
  when: ansible_system == "Linux"

- name: Ensure Metricbeat is started and enabled on boot.
  ansible.windows.win_service:
    name: metricbeat
    state: started
    start_mode: "{{ _metricbeat_win_start_mode }}"
  when: ansible_os_family == "Windows"
