---
# Variables
- name: Import variables
  ansible.builtin.import_tasks: vars.yml
  tags: ['always']

# Install
- name: Install Metricbeat
  ansible.builtin.include_tasks: install.yml
  tags: ['install']

# Configure
- name: Configure Metricbeat
  ansible.builtin.include_tasks: configure.yml
  tags: ['configure']

# Configure Modules
- name: Configure Metricbeat modules
  ansible.builtin.include_tasks: configure-modules.yml
  tags: ['configure', 'modules']
