---
- name: Ensure Metricbeat is started and enabled on boot
  ansible.builtin.service:
    name: metricbeat
    state: started
    enabled: "{{ metricbeat_enable_on_boot }}"
  when: ansible_system == "Linux"
