---
- name: Restart Metricbeat
  ansible.builtin.service:
    name: metricbeat
    state: restarted

- name: Restart Metricbeat on Windows
  ansible.windows.win_service:
    name: metricbeat
    state: restarted
