---
# Module configuration
metricbeat_modules_config: {}

# Modules default configuration
metricbeat_modules_default_config:
  elasticsearch:
    - period: 10s
      metricsets:
        - node
        - node_stats
      hosts:
        - "http://127.0.0.1:9200"
  postgresql:
    - period: 10s
      metricsets:
        - database
        - bgwriter
        - activity
      hosts:
        - "postgres://localhost:5432"
  redis:
    - perdiod: 10s
      metricsets:
        - info
        - keyspace
      hosts:
        - "127.0.0.1:6379"
  system:
    - period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - socket_summary
        - core
        - diskio
      extra:
        process.include_top_n:
          by_cpu: 5
          by_memory: 5
    - period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
    - period: 15m
      metricsets:
        - uptime

# Supported modules by this role
metricbeat_supported_modules:
  - elasticsearch
  - postgresql
  - redis
  - system
