---
# Module configuration
metricbeat_modules_config: {}

# Supported modules by this role
metricbeat_supported_modules:
  - apache
  - elasticsearch
  - mssql
  - mysql
  - nginx
  - php_fpm
  - postgresql
  - redis
  - system

# Modules default configuration
metricbeat_modules_default_config:
  apache:
    - period: 10s
      metricsets:
        - status
      server_status_path: server-status
  elasticsearch:
    - period: 10s
      metricsets:
        - node
        - node_stats
      hosts:
        - "http://127.0.0.1:9200"
  nginx:
    - period: 10s
      metricsets:
        - stubstatus
      hosts:
        - "http://127.0.0.1"
  mssql:
    - period: 10s
      metricsets:
        - "transaction_log"
        - "performance"
      hosts:
        - "sqlserver://localhost"
      username: domain\username
      password: verysecurepassword
  mysql:
    - period: 10s
      metricsets:
        - status
      hosts:
        - "root:secret@tcp(127.0.0.1:3306)/"
  php_fpm:
    - period: 10s
      metricsets:
        - pool
        - process
      hosts:
        - "localhost:8080"
      status_path: "/status"
  postgresql:
    - period: 10s
      metricsets:
        - database
        - bgwriter
        - activity
      hosts:
        - "postgres://localhost:5432"
  redis:
    - period: 10s
      metricsets:
        - info
        - keyspace
      hosts:
        - "127.0.0.1:6379"
  system:
    - period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - socket_summary
        - core
        - diskio
      extra:
        process.include_top_n:
          by_cpu: 5
          by_memory: 5
    - period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
    - period: 15m
      metricsets:
        - uptime

# Additional module default configuration on Linux
metricbeat_additional_default_config:
  system:
    - period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - socket_summary
        - core
        - diskio
      extra:
        process.include_top_n:
          by_cpu: 5
          by_memory: 5
    - period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
    - period: 15m
      metricsets:
        - uptime

# Additional module default configuration on Windows
metricbeat_win_additional_default_config:
  system:
    - period: 10s
      metricsets:
        - cpu
        - memory
        - network
        - process
        - process_summary
        - socket_summary
        - core
        - diskio
      extra:
        process.include_top_n:
          by_cpu: 5
          by_memory: 5
    - period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
    - period: 15m
      metricsets:
        - uptime
